spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
      timeout: 0
      lettuce:
        pool:
          max-active: 8 # ???????????? 8 ????????????
          max-idle: 8 # ????????????????? 8 ????????????
          min-idle: 0 # ????????????????? 0 ????? 0 ? ???
          max-wait: -1 # ????????????????????? -1 ???????